### ISSUE TITLE
Low Priority Crash: "Decoding Error: Invalid UTF-8" when typing in Hebrew

### ISSUE THREAD

**Issue by SonOfLilit** [technomancy/bussard#1]
Not very important.

On Windows 7, with the binary from the website, when typing in Hebrew:

![prtscr capture](https://cloud.githubusercontent.com/assets/14973/10124896/8d21824a-656a-11e5-93aa-8200e06d0f29.png)

**Comment by SonOfLilit** [comment]
BTW, taking a screenshot of that turned out to be very hard. Regular screenshots came out black, I had to alt+tab so it was "in the background" and then I could take a screenshot. Computers, go figure...

**Comment by technomancy** [comment]
AFAICT this is a bug in Love, though it might be fixed in later versions.

**Comment by technomancy** [comment]
I'm able to type Thai characters now, so I'm assuming Hebrew is working as well.
