### ISSUE TITLE
Usability: Accidental quitting

### ISSUE THREAD

**Issue by SonOfLilit** [technomancy/bussard#2]
ESC leaves editor mode. ESC is also a good guess for how to leave the shell. ESC also happens to quit the game, sometimes. This can be very frustrating, especially since things aren't (yet?) persistent by default.

I propose adding an "are you sure you want to leave?" dialogue box.

**Comment by technomancy** [comment]
This would be a good addition. It would also be good to persist repl history across restarts. Most other things should be persisted already, other than login sessions.

**Comment by technomancy** [comment]
This is fixed too.
