### ISSUE TITLE
Usability: Restart

### ISSUE THREAD

**Issue by SonOfLilit** [technomancy/bussard#3]
At the first minute of play, it's very easy to run out of gas, get frustrated and want to restart - which can only be done by quitting and restarting the game. I propose a "restart" button that disappears, say, when you first `login()`.

**Comment by technomancy** [comment]
This actually exists sort of; you can run `ship.ui.abort(true)`, but it needs to be documented and possibly added to a gui.

**Comment by technomancy** [comment]
Just added this to the pause screen in 0df40b7.
